[general]
enableConfigGui = true
enableNameTags = true
allowScrolling = true
nameBasedFeatures = false
[restrict]
restrictInvisibleToOP = false
restrictBasePlateToOP = false
restrictGravityToOP = false
restrictShowArmsToOP = false
restrictSmallToOP = false
restrictNameVisibleToOP = false
restrictRotationToOP = false
restrictAlignToOP = false
restrictResizeToOP = false
resizeWhitelist = []
restrictWhitelist = []
[client]
directNametagOnly = false
nametagRenderDistance = 0
