#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Nov 23 21:41:44 MSK 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=
