#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Oct 14 21:20:16 MSK 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=MakeUp-UltraFast-9.3e.zip
