#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jan 03 21:25:47 MSK 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=ComplementaryReimagined_r5.6.1.zip
