name: Publish to Modrinth

on:
  push:
    branches: [ 1.21.10 ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build .mrpack
        run: |
          mkdir -p build/overrides
          cp -r minecraft/config build/overrides
          cp minecraft/options.txt build/overrides/options.txt
          cp minecraft/servers.dat build/overrides/servers.dat
          cp mrpack/modrinth.index.json build/modrinth.index.json
          cd build && zip -r ../LumintoPack.mrpack .

      - name: Publish
        uses: kir-antipov/mc-publish@v3.3
        with:
          modrinth-id: lumintomods
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: LumintoPack.mrpack
          name: "Luminto Modpack"
          version: "1.21.10-2"
          version-type: release
          changelog: "Автообновление сборки"
          loaders: fabric
          game-versions: 1.21.10